# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Renumber windows
set-option -g renumber-windows on

# Change prefix to CTRL-Space
unbind C-b
set-option -g prefix C-j
bind C-j send-prefix

# Remap jkl; to window selection
bind a select-window -t :1
bind s select-window -t :2
bind d select-window -t :3
bind f select-window -t :4
bind q select-window -t :5
bind w select-window -t :6
bind e select-window -t :7
bind r select-window -t :8
